### ISSUE TITLE
.fill declaration is filling memory as single byte

### ISSUE THREAD

**Issue by luca-yinxing** [alessandropellegrini/z64sim#15]
**Describe the bug**
Cannot use the .fill statement correctly because it fills the memory in the byte size and as big as "size" for "repeat" times. So the creation of arrays initialized with the same value occurs incorrectly, except for some values such as 0.

**To Reproduce**
```asm
.org 0x800
.data
.comm empty_array, 512
filled_array_8: .fill 256, 8, 255
filled_array_4: .fill 256, 4, 255
filled_array_2: .fill 256, 2, 255
.text
main:
	hlt
```

This program will create a memory filled with `ff` for `256*8 + 256*4 + 256*2` bytes.

**Expected behaviour**
The .fill statement should consider the size as .word, .long, .quad and fill with the initialization value according to the size

**Comment by alessandropellegrini** [comment]
Great, thanks!
